version: "3.9"

services:
  backend:
    build:
        context: .
        dockerfile: backend/Dockerfile
    container_name: credit-backend
    ports:
      - "8004:8004"

  frontend:
    build:
        context: .
        dockerfile: frontend/Dockerfile
        args:
          VITE_APP_URL: http://localhost:8004
    container_name: credit-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend